=== Chris22daz/Proyecto-Web-Semantica/agencia_autos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agencia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="auto" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="marca" type="xs:string"/>
                                        <xs:element name="modelo" type="xs:string"/>
                                        <xs:element name="anio" type="xs:integer"/>
                                        <xs:element name="tipo" type="xs:string"/>
                                        <xs:element name="precio" type="xs:decimal"/>
                                        <xs:element name="kilometraje" type="xs:nonNegativeInteger"/>
                                        <xs:element name="transmision" type="xs:string"/>
                                        <xs:element name="estado" type="xs:string"/>
                                        <xs:element name="foto" type="xs:anyURI" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Chris22daz/Proyecto-Web-Semantica/agencia_autos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="agencia_autos.xsl"?>
<agencia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agencia_autos.xsd">
    <titulo>Agencia de Autos ServiDrive</titulo>
    <autos>
        <auto id="A005">
            <marca>Volkswagen</marca>
            <modelo>POL</modelo>
            <anio>2025</anio>
            <tipo>Sedan</tipo>
            <precio>560000</precio>
            <kilometraje>10000</kilometraje>
            <transmision>Manual</transmision>
            <estado>Disponible</estado>
            <foto>/uploads/A005.jpg</foto>
        </auto>
        <auto id="A004">
            <marca>Volkswagen</marca>
            <modelo>Jetta</modelo>
            <anio>2025</anio>
            <tipo>Sedan</tipo>
            <precio>560000</precio>
            <kilometraje>10000</kilometraje>
            <transmision>Automática</transmision>
            <estado>Disponible</estado>
            <foto>/uploads/A004.jpg</foto>
        </auto>
        <auto id="A001">
            <marca>Toyota</marca>
            <modelo>Corolla</modelo>
            <anio>2022</anio>
            <tipo>Sedan</tipo>
            <precio>420000</precio>
            <kilometraje>32000</kilometraje>
            <transmision>Automática</transmision>
            <estado>Disponible</estado>
            <foto>/uploads/A001.jpg</foto>
        </auto>
        <auto id="A002">
            <marca>Honda</marca>
            <modelo>CR-V</modelo>
            <anio>2021</anio>
            <tipo>SUV</tipo>
            <precio>560000</precio>
            <kilometraje>41000</kilometraje>
            <transmision>Automática</transmision>
            <estado>Vendida</estado>
            <foto>/uploads/A002.jpg</foto>
        </auto>
        <auto id="A003">
            <marca>Ford</marca>
            <modelo>Focus</modelo>
            <anio>2020</anio>
            <tipo>Hatchback</tipo>
            <precio>310000</precio>
            <kilometraje>54000</kilometraje>
            <transmision>Manual</transmision>
            <estado>Disponible</estado>
            <foto>/uploads/A003.jpg</foto>
        </auto>
    </autos>
</agencia>
